name: My Workflow
on:
  workflow_dispatch: 
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This step will run successfully"
        
      - name: Step 2
        run: exit 15
        continue-on-error: true
        
      - name: Step 3
        run: echo "This step will still execute, even though Step 2 encountered an error"
        
      - name: Step 4
        run: echo "This step will also execute if the previous steps didn't encounter errors"
